version: "3.8"

services:
  db:
    image: redis:latest
    container_name: "fibonacci-test-redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev

  api:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: "fibonacci-test"
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - dev

networks:
  dev:
    driver: bridge